Adds a new job in ci.yml to check for cucumber feature coverage to be 90%

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -106,3 +106,35 @@ jobs:
           name: screenshots
           path: ${{ github.workspace }}/tmp/screenshots
           if-no-files-found: ignore
+
+  cucumber_coverage:
+    runs-on: ubuntu-latest
+
+    steps:
+      - name: Checkout code
+        uses: actions/checkout@v4
+
+      - name: Set up Ruby
+        uses: ruby/setup-ruby@v1
+        with:
+          ruby-version: .ruby-version
+          bundler-cache: true
+
+      - name: Install dependencies
+        run: bundle install
+
+      - name: Run Cucumber tests with coverage
+        run: |
+          bundle exec cucumber --format pretty --format html --out cucumber_report.html
+          if grep -q "coverage below" coverage/.last_run.json; then
+            echo "Test coverage is below the required threshold"
+            exit 1
+          else
+            echo "Test coverage meets the required threshold"
+          fi
+
+      - name: Upload Cucumber HTML Report
+        uses: actions/upload-artifact@v4
+        with:
+          name: cucumber-report
+          path: cucumber_report.html
